"""
This is a dummy CleanCall class for dry run only, or to be inheritted by casaImagingRoutines.CleanCall.
"""
import copy
import logging
import os
import re

import analysisUtils as au
import numpy as np

from .casaStuff import imhead
from .casaVisRoutines import estimate_mrs

logger = logging.getLogger(__name__)

#region class CleanCall

class CleanCall:

    def __init__(self, infile_list=[], use_chunks=False, nchan=None):

        ############################################
        # Parameters used by the CleanCall object. #
        ############################################

        self.infile_list = infile_list
        self.logfile = None

        ###################################
        # Initialize the clean parameters #
        ###################################

        self.clean_params = {}
        self.reset_params()

        self.use_chunks = use_chunks

        # Allows for consistently overriding the number of channels in the config file.
        # Otherwise the default is -1 (all w/o knowing the number of channels)
        if nchan is not None:
            self.clean_params['nchan'] = nchan

    def __str__(self):
        """
        Return the clean call as a string that can be pasted into
        CASA. Uses the default CASA version.
        """
        #clean_text = 'tclean('
        #kwargs_for_clean = self.kwargs_for_clean()
        #first = True
        #for this_kwarg in kwargs_for_clean:
        #    if first:
        #        first = False
        #    else:
        #        clean_text += ','
        #    string_for_kwarg = str(kwargs_for_clean[this_kwarg])
        #    if type(kwargs_for_clean[this_kwarg]) == type(''):
        #        string_for_kwarg = '"'+string_for_kwarg+'"'
        #    clean_text += str(this_kwarg)+'='+string_for_kwarg
        #clean_text += ')'
        #return clean_text
        #
        #<TODO><DL># return 'tclean('+', '.join("{!s}={!r}".format(k, self.clean_params[k]) for k in self.clean_params.keys())+')'
        kwargs_for_clean = self.kwargs_for_clean()
        return 'tclean('+', '.join("{!s}={!r}".format(k, kwargs_for_clean[k]) for k in kwargs_for_clean.keys())+')'

    #########################
    # Attributes From Files #
    #########################

    # Read parameters from one file

    def reset_params(self):
        """
        Reset the clean call paameters to a dictionary containing only
        the parameters in the supplied files, read in the order that
        they are supplied by the user.
        """

        self.clean_params = {}
        for infile in self.infile_list:
            self.read_one_file(infile)

    def read_one_file(self, fname=None):
        """
        Read the clean call attributes from an input file of the kind
        generated by save_inputs.
        """

        logger.info("Reading a clean input parameter file.")
        logger.info("Reading: "+fname)

        with open(fname, 'r') as infile:

            lines_read = 0
            while True:
                line = infile.readline()
                line = line.replace(" ","")
                line = line.replace("\n","")
                if len(line) == 0:
                    break
                if line[0] == '#' or line == '\n':
                    continue
                if line.count('=') == 0:
                    continue
                exec(re.sub(r'^([a-zA-Z0-9_]+) *= *(.+) *$', r'self.clean_params["\1"] = \2', line) )
                continue

        return()

    #####################
    # Attribute setting #
    #####################

    # Include specific routines only where there is logic to be
    # implemented, else just use "set."

    def set_param(self, key, value, nowarning=False):
        """
        Set a clean parameter to the specified value. Set nowarning to
        suppress a check that the field already exists.
        """
        if key in self.clean_params.keys() or nowarning:
            self.clean_params[key] = value
            return()
        else:
            raise Exception('The clean_params do not currently include key  "'+str(key)+'"')
        return()

    def set_restfreq_ghz(self, value=None):
        """
        Set the rest frequency used for cube imaging. Expects a value in GHz.
        """
        self.clean_params['restfreq']=str(value)+'GHz'
        return()

    def set_reffreq_ghz(self, value=None):
        """
        Set the refrence frequency used in continuum imaging. Expects
        a value in GHz.
        """
        if value is not None:
            self.clean_params['reffreq']=str(value)+'GHz'
        else:
            self.clean_params['reffreq']=''
        return()

    def set_multiscale_clean_scales(self,
                                    key_handler,
                                    config: str,
                                    imaging_method: str="tclean",
                                    ):
        """
        Set the scales for deconvolution in arcseconds. Requires that a
        cell size already be defined so that these can be translated
        into pixel units.

        Args:
            key_handler (handlerTemplate.HandlerTemplate): KeyHandler object
            config (str): Configuration name
            imaging_method (str, optional): Should be one of 'tclean', 'sdintimaging'.
                Defaults to 'tclean'.
        """
        cell_in_pix = self.get_cell_in_arcsec()
        if cell_in_pix is None:
            return()

        clean_scales_auto = key_handler.get_clean_scales_auto_for_config(config)
        if clean_scales_auto:

            logger.info("Setting clean scales automatically")

            # Get parameters for the automatic clean scale handling
            clean_scales_auto_factor = key_handler.get_clean_scales_auto_factor_for_config(config)
            clean_scales_max_las_fraction = key_handler.get_clean_scales_max_las_fraction_for_config(config)

            # Calculate LAS and beam size
            vis = self.get_param("vis")
            mrs_dict = estimate_mrs(vis)
            las = mrs_dict["mrs"]
            beam = self.estimate_synthesised_beam(imaging_method=imaging_method)

            logger.info("Calculated LAS as "+str(las)+" arcsec")
            logger.info("Calculated beam as "+str(beam)+" arcsec")

            # Start with scales of 0 and the beam
            scales = [0, float(beam)]

            # Keep multiplying the scale by the set factor, until we reach the fraction of LAS
            while scales[-1] < clean_scales_max_las_fraction * las:
                scale = scales[-1] * clean_scales_auto_factor
                scales.append(float(scale))

            # Trim off the final scale, since we'll have overshot
            scales = scales[:-1]

            logger.info("Will use scales (arcsec): "+str(scales))

        else:

            logger.info("Setting clean scales manually:")

            clean_scales_arcsec = key_handler.get_clean_scales_arcsec_for_config(config)
            if clean_scales_arcsec is None:
                clean_scales_arcsec = []

            logger.info("clean_scales_arcsec: "+str(clean_scales_arcsec))

            clean_scales_beam = key_handler.get_clean_scales_beam_for_config(config)
            if clean_scales_beam is None:
                clean_scales_beam = []

            logger.info("clean_scales_beam: " + str(clean_scales_beam))

            if len(clean_scales_arcsec) + len(clean_scales_beam) == 0:
                raise ValueError("At least one of clean_scales_arcsec, clean_scales_beam must be defined")

            # If we have beam scales defined, convert to arcsec
            if len(clean_scales_beam) > 0:
                beam = self.estimate_synthesised_beam(imaging_method=imaging_method)

                clean_scales_beam = np.asarray(clean_scales_beam) * beam

            # Combine these lists, make sure they're unique
            scales = list(clean_scales_arcsec) + list(clean_scales_beam)
            scales = [float(s) for s in np.unique(scales)]

        scales_in_pix = []
        for this_scale_arcsec in scales:
            this_scale_pix = this_scale_arcsec/cell_in_pix
            scales_in_pix.append(this_scale_pix)

        # Sort, round, make sure unique
        scales_in_pix.sort()
        scales_in_pix = [np.round(t) for t in scales_in_pix]
        scales_in_pix = [int(s) for s in np.unique(scales_in_pix)]

        self.clean_params['scales'] = copy.deepcopy(scales_in_pix)

        return True

    def estimate_synthesised_beam(
        self,
        imaging_method: str = "tclean",
    ):
        """Estimate the synthesised beam, either from an existing image or from the visibility data

        Args:
            imaging_method (str, optional): either 'tclean' or 'sdintimaging'. Defaults to 'tclean'.
        """

        im_name = self.get_param("imagename")

        # Get out expected image name
        if imaging_method == "tclean":
            im = f"{im_name}.image"
        elif imaging_method == "sdintimaging":
            im = f"{im_name}.int.cube"
        else:
            raise ValueError("Unknown imaging method: " + str(imaging_method))

        # If available, pull from the existing image
        if os.path.exists(im):
            
            logger.info("Getting beam from existing image")

            # Get average of bmaj/bmin
            bmaj = imhead(imagename=im, mode="get", hdkey="bmaj")
            bmin = imhead(imagename=im, mode="get", hdkey="bmin")
            beam = (bmaj["value"] + bmin["value"]) / 2

        # Otherwise, estimate using visibilities
        else:

            logger.info("Estimating beam from visibilities")
            
            vis = self.get_param("vis")
            beam = au.estimateSynthesizedBeam(vis)

        return beam

    def set_round_uvtaper_arcsec(self, taper=0.0):
        """
        Sets a round outer UV taper of the value provided in units of arcseconds.
        """
        self.clean_params['uvtaper'] = [str(taper)+'arcsec',str(taper)+'arcsec','0deg']
        return()

    ####################
    # Attribute access #
    ####################

    def get_cell_in_arcsec(self):
        """
        Return the cell size (assumed in arcsec string format) as a float in arcsec.
        """
        if len(self.clean_params['cell']) == 0:
            return(None)
        if self.clean_params['cell'] is None:
            return(None)
        if type(self.clean_params['cell']) == type([]):
            cell_string = self.clean_params['cell'][0]
        else:
            cell_string = self.clean_params['cell']
        # We don't worry about arcmin or deg right now - can adjust if needed
        return(float((cell_string).replace('arcsec','')))

    def has_param(self, key=None):
        """
        Check if an attribute is in the clean parameter dictionary.
        """
        if key is None:
            return(False)
        if key in self.clean_params.keys():
            return(True)
        return(False)

    def get_param(self, key=None):
        """
        Get an attribute by its string name.
        """
        if key is None:
            return(None)
        if key in self.clean_params.keys():
            return(self.clean_params[key])
        else:
            logger.warning('clean_params does not have an attribute named "'+str(key)+'"')
            return(None)

    def return_chunked_channel_ranges(self, chunksize=1):
        '''
        Set the channel ranges split up large cubes into smaller channel chunks.

        Parameters
        ----------
        chunksize : int
            Number of channels to image together in a chunk.
        '''

        if not self.use_chunks:
            logger.warn("use_chunks has not been enabled. Call `CleanCall` with `use_chunks=True`.")
            return

        if not isinstance(chunksize, int):
            raise ValueError("chunksize must be an integer.")

        if chunksize < 1:
            raise ValueError("chunksize must be positive.")

        nchan = self.clean_params['nchan']

        # Group by requested chunk size
        nchunks = nchan // chunksize
        nleft = nchan % chunksize

        self._num_chunks = nchunks

        if nchunks == 1:
            logger.error("Given chunksize {0} does not require chunking the cleaning job.".format(chunksize) +
                        "Image as a whole cube or change chunksize.")
            #TODO: fix this with something graceful
            return

        # Arange defined the upper and lower
        chunk_limits = np.append(np.arange(0, nchan - nleft, chunksize), nchan - nleft)

        # If there's a remainder, tack that on as another chunk:
        if nleft > 0:
            chunk_limits = np.append(chunk_limits, nchan)

        chunk_starts = chunk_limits[:-1]
        chunk_ends = chunk_limits[1:] - 1

        # The difference between these should be chunksize - 1 for all but the last one:
        assert all((chunk_ends - chunk_starts)[:-1] == chunksize - 1)

        return chunk_starts.astype(int), chunk_ends.astype(int)

    ##################################
    # Hook up to executions of clean #
    ##################################

    def kwargs_for_clean(
        self,
        casaversion='5.6',
        ):
        """
        Output keyword arguments to be fed into (t)clean.
        """

        known_versions = ['5.4','5.6']
        if casaversion not in known_versions:
            logger.error('CASA simple version '+str(casaversion)+' not in known version list.')
            return(None)

        #<TODO># Work on adapting to different CASA versions
        #<TODO><DL># use inspect package? provide CASA version compatibility inside recipe.clean file, then do the CASA version check only when executing it?

        return(self.clean_params)

#endregion




def CleanCallFunctionDecorator(func):
    def func_wrapper(*args, **kwargs):
        for k in kwargs.keys():
            #print('CleanCallFunctionDecorator', kwargs[k], type(kwargs[k]), isinstance(kwargs[k], CleanCall))
            if k == 'clean_call':
                if kwargs[k] is None:
                    logger.warning("Require a clean_call object. Returning.")
                    return
                elif not isinstance(kwargs[k], CleanCall):
                    logger.error('Error! Invalid clean_call! It should be a CleanCall instance!')
                    raise Exception('Error! Invalid clean_call! It should be a CleanCall instance!')
                    return
        return func(*args, **kwargs)
    return func_wrapper






